config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls', namespace='user')),
    path('', include('core.urls', namespace='core')),
]

core/urls.py
from django.urls import path
from .views.views import MovieList, MovieDetail

app_name = 'core'

urlpatterns = [
    path('', MovieList.as_view(), name='MovieList'),
    path('movie/<int:pk>', MovieDetail.as_view(), name='MovieDetail'),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from user import views

app_name = 'user'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

core/models.py
from django.db import models
from django.conf import settings
from .managers import PersonManager, MovieManager


class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audience'),
        (RATED_PG, 'PG - Parental Guidance Suggested'),
        (RATED_R, 'R - Restricted'),
    )
    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(
        choices=RATINGS,
        default=NOT_RATED
    )
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)
    director = models.ForeignKey(to='Person', on_delete=models.SET_NULL, related_name='directed', null=True, blank=True)
    writers = models.ManyToManyField(to='Person', related_name='writing_credits', blank=True)
    actors = models.ManyToManyField(to='Person', through='Role', related_name='acting_credits', blank=True)

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return f'{self.title} ({self.year})'

    objects = models.Manager()
    related_objects = MovieManager()


class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    class Meta:
        ordering = (
            'last_name', 'first_name')

    def __str__(self):
        if self.died:
            return '{}, {} ({}-{})'.format(
                self.last_name,
                self.first_name,
                self.born,
                self.died)
        return '{}, {} ({})'.format(
            self.last_name,
            self.first_name,
            self.born)

    objects = models.Manager()
    related_objects = PersonManager()


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return f"{self.movie.id} {self.person.id} {self.name}"

    class Meta:
        unique_together = ('movie', 'person', 'name')


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, "",),
        (DOWN, "",),
    )

    value = models.SmallIntegerField(
        choices=VALUE_CHOICES,
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user', 'movie')

user/models.py
from django.db import models

# Create your models here.

core/views/views.py
from django.views.generic import (
    ListView,
    DetailView,
)
from core.models import Movie, Person


class MovieList(ListView):
    model = Movie


class MovieDetail(DetailView):
    model = Movie


class PersonDetail(DetailView):
    queryset = Person.related_objects.all_with_prefetch_movies()


class MovieDetail(DetailView):
    queryset = (
        Movie.related_objects.all_with_related_persons())

user/views.py
from django.contrib.auth.forms import (
    UserCreationForm,
)
from django.urls import (
    reverse_lazy,
)
from django.views.generic import (
    CreateView,
)


class RegisterView(CreateView):
    template_name = 'user/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy(
        'core:MovieList')

core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }} - {{ block.super }}
{% endblock %}

{% block main %}
    <h1>{{ object }}</h1>
    <p class="lead">
        {{ object.plot }}
    </p>
{% endblock %}

{% block sidebar %}
    <div>
        This movie is rated:
        <span class="badge badge-primary">
  {{ object.get_rating_display }}
  </span>
    </div>
{% endblock %}

core/templates/core/movie_list.html
{% extends 'base.html' %}
{% block title %}All The  Movies:{% endblock %}
{% block main %}
    <ul>
        {% for movie in object_list %}
            <li>
                <a href="{% url 'core:MovieDetail' pk=movie.id %}">{{ movie }}</a>
            </li>
        {% empty %}
            <li>
                No movies found.
            </li>
        {% endfor %}
    </ul>
    {% if is_paginated %}
        <nav>
            <ul class="pagination">
                <li class="page-item">
                    <a href="{% url 'core:MovieList' %}?page=1" class="page-link">First</a>
                </li>
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a href="{% url 'core:MovieList' %}?page={{ page_obj.previous_page_number }}" class="page-link">
                            {{ page_obj.previous_page_number }}
                        </a>
                    </li>
                {% endif %}
                <li class="page-item active">
                    <a href="{% url 'core:MovieList' %}?page={{ page_obj.number }}" class="page-link">
                        {{ page_obj.number }}
                    </a>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="{% url 'core:MovieList' %}?page={{ page_obj.next_page_number }}" class="page-link">
                            {{ page_obj.next_page_number }}
                        </a>
                    </li>
                {% endif %}
                <li class="page-item">
                    <a href="{% url 'core:MovieList' %}?page=last" class="page-link">
                        Last
                    </a>
                </li>
            </ul>
        </nav>
    {% endif %}
{% endblock %}

core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.first_name }}
    {{ object.last_name }}
{% endblock %}

{% block main %}

    <h1>{{ object }}</h1>
    <h2>Actor</h2>
    <ul>
        {% for role in object.role_set.all %}
            <li>
                <a href="{% url 'core:MovieDetail' role.movie.id %}">
                    {{ role.movie }}
                </a>:
                {{ role.name }}
            </li>
        {% endfor %}
    </ul>
    <h2>Writer</h2>
    <ul>
        {% for movie in object.writing_credits.all %}
            <li>
                <a href="{% url 'core:MovieDetail' movie.id %}">
                    {{ movie }}
                </a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <title>{% block title %}MyMDB{% endblock %}</title>
    <style>
        .mymdb-masthead {
            background-color: #EEEEEE;
            margin-bottom: 1em;
        }
    </style>
</head>
<body>
<div class="mymdb-masthead">
    <div class="container">
        <nav class="nav">
            <div class="navbar-brand">MyMDB</div>
            <a class="nav-link" href="{% url 'core:MovieList' %}">Movies</a>
        </nav>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-8 mymdb-main">
            {% block main %}{% endblock %}
        </div>
        <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
            {% block sidebar %}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>

user/templates/user/login.html
{% extends "base.html" %}

{% block title %}
    Login - {{ block.super }}
{% endblock %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button
                class="btn btn-primary">
            Log In
        </button>
    </form>
{% endblock %}

user/templates/user/register.html
{% extends "base.html" %}

{% block main %}
    <h1>Register for MyMDB</h1>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <button
                type="submit"
                class="btn btn-primary">
            Register
        </button>
    </form>
{% endblock %}